default: &default
  adapter: postgresql
  encoding: UTF8
  host: localhost
  pool: 5

development:
  <<: *default
  database: monstercards_development

test:
  <<: *default
  database: monstercards_test
