# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 412d36a709fdcc73beadd56a5ae4b40b4730755d6200d20fd041b73fd4bb35dfaf75761400f02af050907264f11ff4fabe40aeb507eb7724306793df15b3832a

test:
  secret_key_base: e076abd88dd70e5aa5434e983260fd638fb0ca679284a55334ed05c53b827576f6d4ba31f6948766bb5b70b61cb141bac95b7445bc78cb4aa45b40f02142e47e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
